### ISSUE TITLE
latest image (1.8.0) do not work

### ISSUE THREAD

**Issue by alexvish** [rhpds/openshift-gitea-image#4]
Log:

2019/05/04 19:39:28 [1;31m[...s/setting/setting.go:729 NewContext()] [E] error saving generating JWT secret to custom config: open /home/gitea/conf/app.ini: read-only file system[0m

Workaround:
Change image in gitea deployment config:
image: 'docker.io/wkulhanek/gitea:1.7.5'

**Comment by flothemaker** [comment]
Same problem with image 1.8.1

**Comment by MohamedTalhaoui** [comment]
Does anyone having any idea about the root cause ?
I can understand the error since, at startup, gitea tries to write the generated token in the app.ini which is mounted from a configMap and therefore read only.
I cannot get why using image 1.7.5 solves the issue.
I was expecting the fix to be on the openshift template.
Any idea ?

**Comment by rilindo** [comment]
Note that you don't need to edit the template if you do need to over the version - you can just pass the versions as a param:

```
oc new-app -f https://raw.githubusercontent.com/wkulhanek/docker-openshift-gitea/master/openshift/gitea-ephemeral-template.yaml --param=HOSTNAME=gitea-demo.yourdomain.com --param=GITEA_VERSION=1.7.5
```

**Comment by simbo1905** [comment]
I have created PR #5 to fix this. Until it is merged and the image deployed you can use my copy of the fix to gitea 1.9.2

```sh
oc new-app -f https://raw.githubusercontent.com/wkulhanek/docker-openshift-gitea/master/openshift/gitea-persistent-template.yaml \
  --param=HOSTNAME=${GITEA_URL} \
  --param=GITEA_VERSION=1.9.2 
  --param=GITEA_IMAGE=docker.io/simonmassey/gitea
```

**Comment by Mundo-Dev0ps** [comment]
Hello @simbo1905 , what do you change in Dockerfile?, I am making an image based on alpine but i get the same error: "saving generating JWT secret to custom config: open /home/gitea/conf/app.ini: read-only file system"

**Comment by simbo1905** [comment]
Hi @jonathan-velasco 

I posted a link above to the PR with the fix above. The change is to the script that launches gitea here: https://github.com/wkulhanek/docker-openshift-gitea/pull/5/files

Simon

**Comment by Mundo-Dev0ps** [comment]
Hi @simbo1905 ,

Ty very much, I make pull request for dockerfile with alpine base image for if you need it 
[PR 7](https://github.com/wkulhanek/docker-openshift-gitea/pull/7/commits/21dfc1de962f50d0238a3cc576e54a2bd072cf8c)

Regards

**Comment by zdzichu** [comment]
Hey @wkulhanek , any chance of getting this fixed (by PR 5)?

**Comment by wkulhanek** [comment]
@zdzichu Sorry, somehow I missed this. What exactly is the problem? I'm actually at 1.11.3 now with this image and have been running this forever. Or course I never run the image directly (or through the template) anymore but only through the operator.

**Comment by wkulhanek** [comment]
I updated the app.ini in the template. This is the same that I use in the operator. Let me know if it works now. @zdzichu

**Comment by zdzichu** [comment]
I'm surprised it works for you. Nevetherless, the summary of problems:
- oauth2 has been enabled by default in gitea
- when gitea starts and there are no JWT_SECRET, LFS_JWT_SECRET in config file, gitea tries to generate the secrets and store them in app.ini; this **fails** because filesystem is read-only

Possible solutions:
- generate secrets and store them in configmap creating app.ini
- modify config map to disable oauth2 support
- provide writable configuration - that's what mentioned PR does

**Comment by wkulhanek** [comment]
Yeah. I disabled oauth2...

**Comment by wkulhanek** [comment]
Let me investigate the writable config.

**Comment by wkulhanek** [comment]
That PR won't work - at least not for subsequent starts. I am closing this issue because I disabled OAuth2 for now.
